<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SvgBillBoard.Application\SvgBillBoard.Application.csproj" />
    <ProjectReference Include="..\SvgBillBoard.Infrastructure\SvgBillBoard.Infrastructure.csproj" />
  </ItemGroup>
	<ItemGroup>
		<Content Update="appsettings.Testing.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Middleware\" />
    <Folder Include="OpenApi\" />
  </ItemGroup>

</Project>
