- name: Restore
  run: dotnet restore ./svgBillBoard/YourSolution.sln

- name: Build
  run: dotnet build ./svgBillBoard/YourSolution.sln --no-restore --configuration Release

- name: Test
  run: dotnet test ./svgBillBoard/YourSolution.sln --no-build --configuration Releasename: .NET CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ./svgBillBoard/svgBillBoard.slnx

      - name: Build
        run: dotnet build ./svgBillBoard/svgBillBoard.slnx --no-restore --configuration Release

      - name: Test
        run: dotnet test ./svgBillBoard/svgBillBoard.slnx --no-build --configuration Release