name: .NET CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ./svgBillBoard/svgBillBoard.slnx

      - name: Build
        run: dotnet build ./svgBillBoard/svgBillBoard.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test ./svgBillBoard/svgBillBoard.slnx --configuration Release --no-build
